name: Playwright Test Workflow

on:
  push:
    branches: [ "main", "master", "develop" ]  # Definir las ramas donde se ejecutarán las pruebas
  pull_request:
    branches: [ "main", "master", "develop" ]
  schedule:
    - cron: '0 0 * * *'  # Ejecutar diariamente a medianoche
  workflow_dispatch:  # Permite la ejecución manual desde la interfaz de GitHub

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest  # El trabajo se ejecutará en Ubuntu

    steps:
    # Paso 1: Hacer checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Paso 2: Configurar Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Cambia la versión de Node.js según tu configuración

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: |
        npm install
        npm install allure-playwright  # Asegúrate de instalar Allure Playwright si no está instalado

    # Paso 4: Ejecutar pruebas de Playwright con el reporte Allure
    - name: Run Playwright tests with Allure reporter
      run: |
        npx playwright test --reporter=allure-playwright

    # Paso 5: Copiar los resultados generados por Allure
    - name: Copy Allure results
      run: |
        mkdir allure-results
        cp -r test-results/* allure-results/

    # Paso 6: Generar el reporte Allure
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()  # Siempre ejecutar este paso, incluso si falla algún test
      with:
        allure_results: allure-results
        keep_reports: 20  # Mantener los últimos 20 reportes generados

    # Paso 7: Desplegar el reporte a GitHub Pages
    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages  # La rama donde se publicarán los reportes
        publish_dir: allure-report  # La carpeta donde se generarán los reportes Allure
        force_orphan: true
